# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 329cc8e3f1a3c778bb88fc4ab61e5bd034ae46ca9e56c94050d0c1b8f6af58a981e48110ec86131b5e466bc100c418f5e9e9cdfe6144e97957a3ece770226856

test:
  secret_key_base: 1a796b7ce4b52bcf1f06eb05aaed8c7f0fcfb9d3b20e95c4dcfc3a8425b1cc062c6a6b520cf35ee4059459ee14e7be192c050d031afe297eb9293885d11dc8a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
